### Login as administrator and receive token
POST {{host}}/administrator/login
Content-Type: application/json

{
  "email": "admin@course_platform.com",
  "password": "admin"
}

> {%
    client.global.set("auth_token", response.body.token);

    client.test("Admin login successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Response does not contain token");
    });
%}

### Create a new student with admin token
POST {{host}}/students
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "{{$random.email}}@course_platform.com",
  "password": "{{$random.alphanumeric(7)}}",
  "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  "full_name": "{{$random.alphanumeric(7)}} {{$random.alphanumeric(10)}}"
}

> {%
    client.test("Admin create student successfully", function () {
        client.assert(response.status === 201, "Response status is not 200");
    });
%}

### Get all students with admin token
GET {{host}}/students
Authorization: Bearer {{auth_token}}

> {%
    client.test("Get actual students successfully", function () {
        client.assert(response.contentType.mimeType === "application/json", "Response content type is not application/json")
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length > 0, "Response does not contain students");
    });
%}

### Create a new teacher with admin token
POST {{host}}/teachers
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "{{$random.email}}",
  "password": "123456",
  "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  "full_name": "Ivan Ivanenko",
  "description": "Ivan Ivanenko is a professional teacher with 10 years of experience in teaching computer science",
  "date_of_birth": "{{$isoTimestamp}}",
  "education": "Ivan Ivanenko has a master's degree in computer science from the University of California, Berkeley"
}

> {%
    client.test("Admin create teacher successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Get all teachers with admin token
GET {{host}}/teachers
Authorization: Bearer {{auth_token}}

> {%
    client.test("Get actual teachers successfully", function () {
        client.assert(response.contentType.mimeType === "application/json", "Response content type is not application/json")
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length > 0, "Response does not contain students");
    });
%}

### Create a new course with admin token
POST {{host}}/courses
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "iOS Development",
  "description": "This course is designed to help students with no prior experience in computer science to learn the basics of programming and computer science",
  "image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  "teacher_id": 6
}

> {%
    client.test("Admin create course successfully", function () {
        client.assert(response.status === 201, "Response status is not 200");
    });
%}