### Login as student and receive token
POST {{host}}/student/login
Content-Type: application/json

{
  "email": "2uYjG4I@kcpOQG.de@course_platform.com",
  "password": "YQiHB8C"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Get all courses
GET {{host}}/courses/student
Authorization: Bearer {{auth_token}}

### Get subject by id and for student
GET {{host}}/courses/subject/7/student/1
Authorization: Bearer {{auth_token}}

### Upload work
POST {{host}}/students/work
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "subject_id": 5,
  "files": [
    {
      "name": "file",
      "url": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
    },
    {
      "name": "file1",
      "url": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
    }
  ]
}

### Get student work
GET {{host}}/courses/subject/2/student/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTE0NzMyMjcsInJvbGUiOiJzdHVkZW50IiwidXNlcl9pZCI6MX0.lJkixXQ38LkaI5a7oH59CM2lqpp3ZrZQlNtPUxezLeA