### Login as teacher and receive token
POST {{host}}/teacher/login
Content-Type: application/json

{
  "email": "pavlo_general@course_platform.com",
  "password": "123456"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Entroll student to course
POST {{host}}/courses/enroll
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "course_id": 9,
  "student_id": 4
}

### Get all courses by teacher id
GET {{host}}/courses/teacher
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Add Module to course
POST {{host}}/courses/9/module
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Module 2"
}