### Login as teacher and receive token
POST {{host}}/teacher/login
Content-Type: application/json

{
  "email": "antonandrusenko@gmail.com",
  "password": "pupkin1234"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Entroll student to course
POST {{host}}/courses/enroll
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "course_id": 1,
  "student_id": 7
}

### Get all courses by teacher id
GET {{host}}/courses/teacher
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Add Module to course
POST {{host}}/courses/1/module
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Module 2"
}

### Add Lecture lesson to module without files
POST {{host}}/courses/module/2/subject
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Lesson {{$random.alphanumeric(5)}}",
  "description": "Lesson {{$random.alphanumeric(5)}} description",
  "type": "Lecture",
  "due_date": "{{$isoTimestamp}}"
}

### Add Task Lesson to module with files
POST {{host}}/courses/module/2/subject
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Lesson {{$random.alphanumeric(5)}}",
  "description": "Lesson {{$random.alphanumeric(10)}} description",
  "type": "Task",
  "due_date": "{{$isoTimestamp}}",
  "files": [
    {
      "name": "file1",
      "url": "http://file1.com"
    },
    {
      "name": "file2",
      "url": "http://file2.com"
    }
  ]
}

### Get details of course by id
GET {{host}}/courses/5
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get student work
GET {{host}}/courses/subject/5/student/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Grade student work
POST {{host}}/teachers/grade
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "student_work_id": 10,
  "grade": 10
}
